dist: trusty
sudo: false

language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

script: ./gradlew build checkstyle -Dorg.gradle.daemon=false

after_success:
  - ./scripts/publish-javadoc

deploy:
  - provider: releases
    api_key:
      secure: "ogfGQQxY4I5Rwdcoj9qMOL/+unMokUmCdIioBMEhc0UDEa2kbosLIl9lc0OUg38remkQakwiiab/jUZmTGe6/CjAeaGD72FyV3yzx8qdOmBLM3D26xpZ/FdL9qJme5AoVhjba3HaUfl84p/ayxlJzU4GRCDDiVN1aZLFWn9ugLv7kaVakKeJc19t2Qqk8ebnnt1/ItxiDNx6UasVy2mrbZ27Nz4WRkGcorqUQ52Ls/WL/UVJVcZHdY3CU8+dRap+6I82r4W8QhYUMUxtEfOC6z6ataGdkuIYrTP/wH956t1E37Vl6asGPQScht77xhOw9YTM3Ms4lg1bQ/0IIbGM1iVGrHj9KI8I+U/oyHcmdruyB2vXqHuuP4kuL3or8FGFULRQRgrz7/trlzGAs6jrcdUaKa3AhfyvdddZzsuQYKRzQB4diJji+3j8v38V8yGPK+D0VTu/mFA01LsFTjLmnxtU012pp21y+cFt7X028HpiOZU2VixAZCaQr+zfdbzRQMXsyrbHWQfw6P7SCtKf5syjpyYJbYNqfpKq1wGQcX4LHwcmkLauKtpqE7A7sqd1je/4bUqiE17mwfASd5Tj0ISr1P2bcZ1f1sRAeFsggP2ulU5gq5E/MjtWiMpcmx8xXe/14UDCh/Z39luhnoR3t1MpNvqcB3M5msBnw39gzPY="
    skip_cleanup: true
    file_glob: true
    file:
      - "minigames-api/build/libs/*.jar"
      - "minigames-core/build/libs/*-shaded.jar"
      - "natrolite-api/build/libs/*.jar"
      - "natrolite-core/build/libs/*-shaded.jar"
    on:
      tags: true
      jdk: oraclejdk8
      repo: natrolite/natrolite
  - provider: script
    skip_cleanup: true
    script: ./gradlew publish -PdeployUrl="${DEPLOY_URL}" -PdeployUser="${DEPLOY_USER}" -PdeployPass="${DEPLOY_PASS}"
    on:
      tags: true
      jdk: oraclejdk8
      repo: natrolite/natrolite

matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk9

branches:
  except:
    - gh-pages

notifications:
  email: false

env:
  global:
    secure: "lcV9VzSIvmGpfjpia1VuXgX0FZXqqE7i+9gmug/ojyYsTUSmdJPXgrA+7k7V6HdttBcYSGBjIFvdq76pPjh8opGlUZPyfGlTYwzK7ZzL02hT/lz6h/IiL70vqEKdPcd/QSPmHGoEEoWC4orFg3WAb8D8cBeBoYO46CPwnLmCysNTI52/NdqKaUv5bCvWalFA4z9rv6Gd/hF4sZOzhmh4UZkcoNjYPfZ1O9z6YV6ngTdnPpzrrnDgKPlFDf7NPTGXQFu+uSTYFJv0yiFD+KPWJO/swle3LuHOgH4cROlsHbRI/T66ug4uyx/0txFDlFhs+IcZ7/uzglBr0V6TjCTJNAHtSSS1DJiM+z1ba0BGpB9lmJxIq8Sgex4/qhHzfK6aO/viuqxWAZRoU99V6EytyvU8bbMal82zdxYhHgrnTyz0Z55MkYVvtUf+c0Q2eZUlX3jtgHsQ59ofstcofi4/kh8mZVJQ5izvTo4CoOY67SEVx2CWC6bkGjFzxfGx4sFrPGG1hO0ILzpQI+5oozCILkv6Jb7e9Tz+jLybmHTUlG44bGw/oH2TIw0+ZGPdeM+owcDYe3ghYjHZAT+iX3QdjbK4H8czD6ZISvWrATobmaXP0Rna+KUQPkTskn0MVu2wWEMwYtKjbi+saxQA6Xod05ZlTQifdHm+hsaNWcQP6Ac="