language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9

script: ./scripts/build

matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk9

branches:
  except:
    - gh-pages

notifications:
  email: false
